version: "3"

services:
  react:
    image: react:dev
    volumes:
      - './gallery/:/app'
      - '/app/node_modules'
      - '/app/package.json'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - opencvserver
    depends_on:
      - opencvserver

  opencvserver:
    image: imageserver
    volumes:
      - './flask/:/app'
    ports:
      - 5001:5000
    environment:
      - CHOKIDAR_USEPOLLING=true




