version: "3"

services:
  react:
    image: react:dev
    volumes:
      - './gallery/:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      testing_net:
          ipv4_address: 172.18.1.3
    depends_on:
      - opencvserver

  opencvserver:
    image: imageserver
    volumes:
      - './flask/:/app'
    ports:
      - 5001:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      testing_net:
        ipv4_address: 172.18.1.2


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16



